# Add Tasks to Project
steps:
  - name: golang:1.23
    args:
      - run
      - "main.go"
      - "--host-pid"
      - "$_HOST_PID"
      - "--base-folder"
      - ${_ROOT_DIR}
      - "--bucket"
      - "$_BUCKET_NAME"
    id: Build
    entrypoint: go
    dir: "${_TASK_DIR}"
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _TASK_DIR: utils/task-tool
  _ROOT_DIR: ../../
  _BUCKET_NAME: q2-25-tech-day-host-score-assets
  _HOST_PID: $PROJECT_ID
  