---
blueprint_name: hpc-slurm

vars:
  project_id: "%%CLIENT_PROJECT_ID%%"
  deployment_name: "hpc-slurm"
  region: "%%LOCATION%%"
  zone: "%%LOCATION%%-b"

# Documentation for each of the modules used below can be found at
# https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/main/modules/README.md

deployment_groups:
  - group: primary
    modules:
      - id: network
        source: modules/network/vpc

      - id: private_service_access
        source: community/modules/network/private-service-access
        use: [network]

      - id: homefs
        source: modules/file-system/filestore
        use: [network, private_service_access]
        settings:
          local_mount: /home

      - id: python
        source: modules/scripts/startup-script
        settings:
          runners:
            - type: shell
              destination: "python.sh"
              content: |
                #!/bin/bash
                set -ex
                sudo yum -y install python3 python3-pip

      - id: compute_nodeset
        source: community/modules/compute/schedmd-slurm-gcp-v6-nodeset
        use: [network, python]
        settings:
          node_count_dynamic_max: 3
          allow_automatic_updates: false
          machine_type: e2-standard-2
          on_host_maintenance: MIGRATE # Required for e2 images

      - id: compute_partition
        source: community/modules/compute/schedmd-slurm-gcp-v6-partition
        use:
          - compute_nodeset
        settings:
          partition_name: compute
          is_default: true
          exclusive: false

      - id: slurm_login
        source: community/modules/scheduler/schedmd-slurm-gcp-v6-login
        use: [network]
        settings:
          machine_type: e2-standard-2
          enable_login_public_ips: true

      - id: slurm_controller
        source: community/modules/scheduler/schedmd-slurm-gcp-v6-controller
        use:
          - network
          - compute_partition
          - homefs
          - slurm_login
        settings:
          enable_controller_public_ips: true
